import { Tattoo } from "../types/tattoo";

export const mockTattoos: Tattoo[] = [
  {
    id: "1",
    imageUrl: "https://images.unsplash.com/photo-1558355637-e991f0422e08?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    title: "Rose",
    style: "American Traditional",
    price: 150,
    description: "Classic American Traditional rose with bold outlines and rich color. A timeless tattoo design featuring a fully bloomed rose with stem and leaves.",
    keywords: ["American Traditional"],
    labels: [],
    colors: ["Full Color"],
    sizes: ["Medium"]
  },
  {
    id: "2",
    imageUrl: "https://images.unsplash.com/photo-1641402027551-6a2fbf05b356?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    title: "Skull",
    style: "American Traditional",
    price: 200,
    description: "Bold traditional skull design with deep dark sockets and strong linework. A classic memento mori symbol rendered in traditional flash style.",
    keywords: ["American Traditional"],
    labels: ["Skull"],
    colors: ["Black & Grey"],
    sizes: ["Large"]
  },
  {
    id: "3",
    imageUrl: "https://images.unsplash.com/photo-1733517300774-f1f1607d851b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    title: "Mandala Dotwork",
    style: "Fine Line",
    price: 180,
    description: "Modern sacred geometry design with precise dotwork and circular mandala patterns. Intricate geometric shapes create a meditative, eye-catching piece.",
    keywords: ["Fine Line"],
    labels: [],
    colors: ["Black & Grey"],
    sizes: ["Medium"]
  },
  {
    id: "4",
    imageUrl: "https://images.unsplash.com/photo-1775724861935-e60a977c3e03?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    title: "Lotus",
    style: "Neo Traditional",
    price: 160,
    description: "Delicate lotus flower in bloom with layered petals. Symbolizes purity, enlightenment, and rebirth in a minimalist fine-line style.",
    keywords: ["Neo Traditional"],
    labels: [],
    colors: ["Black & Grey"],
    sizes: ["Medium"]
  },
  {
    id: "5",
    imageUrl: "https://images.unsplash.com/photo-1654338776478-b8f90696fd15?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    title: "Flash Wall",
    style: "American Traditional",
    price: 220,
    description: "Classic tattoo studio flash wall featuring iconic American Traditional designs — anchors, roses, eagles, and daggers — the building blocks of tattoo culture.",
    keywords: ["American Traditional"],
    labels: [],
    colors: ["Full Color"],
    sizes: ["Large"]
  },
  {
    id: "6",
    imageUrl: "https://images.unsplash.com/photo-1712027858623-feaadeec9c0e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    title: "Dragon",
    style: "Neo Traditional",
    price: 280,
    description: "Powerful dragon illustration with bold outlines and vibrant color. Features intricate scale detail and dynamic pose perfect for a sleeve or back piece.",
    keywords: ["Neo Traditional"],
    labels: [],
    colors: ["Full Color"],
    sizes: ["Large"]
  },
  {
    id: "7",
    imageUrl: "https://images.unsplash.com/photo-1521308452854-e037c0062a1e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    title: "Flash Art Sheet",
    style: "American Traditional",
    price: 130,
    description: "Hand-drawn tattoo flash art on paper — the traditional way artists display their designs. Features multiple classic motifs ready to be inked.",
    keywords: ["American Traditional"],
    labels: [],
    colors: ["Black & Grey"],
    sizes: ["Small"]
  },
  {
    id: "8",
    imageUrl: "https://images.unsplash.com/photo-1732019065219-5a073b8fd6e0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    title: "Wolf",
    style: "Neo Traditional",
    price: 240,
    description: "Majestic wolf rendered in deep black and grey with detailed fur texture. A symbol of loyalty, strength and the untamed wilderness.",
    keywords: ["Neo Traditional"],
    labels: [],
    colors: ["Black & Grey"],
    sizes: ["Large"]
  },
  {
    id: "9",
    imageUrl: "https://images.unsplash.com/photo-1616486813695-0cefd7ad6485?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    title: "Phoenix",
    style: "American Traditional",
    price: 290,
    description: "Mythical phoenix bird rising in vibrant orange and red hues. Symbolizes rebirth, renewal, and transformation — perfect for a meaningful large piece.",
    keywords: ["American Traditional"],
    labels: [],
    colors: ["Full Color"],
    sizes: ["Large"]
  },
  {
    id: "10",
    imageUrl: "https://images.unsplash.com/photo-1537209383625-19584677a4d3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    title: "Tattoo Artist",
    style: "Fine Line",
    price: 170,
    description: "A tattoo artist at work, crafting a custom design with precision and care. The art of tattooing is as much about the artist's hand as the design itself.",
    keywords: ["Fine Line"],
    labels: [],
    colors: ["Black & Grey"],
    sizes: ["Medium"]
  },
  {
    id: "11",
    imageUrl: "https://images.unsplash.com/photo-1775135332562-9ff99e65a616?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    title: "Traditional Ink",
    style: "American Traditional",
    price: 110,
    description: "Close-up of fresh traditional tattoo ink on skin — bold, clean lines and vibrant pigment that define the American Traditional style.",
    keywords: ["American Traditional"],
    labels: [],
    colors: ["Full Color"],
    sizes: ["Small"]
  },
  {
    id: "12",
    imageUrl: "https://images.unsplash.com/photo-1744946174053-2ced46e0c3d9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    title: "Tiger",
    style: "American Traditional",
    price: 260,
    description: "Traditional tiger face with bold black stripes, golden eyes and sharp detail. A powerful symbol of strength, ferocity, and courage.",
    keywords: ["American Traditional"],
    labels: [],
    colors: ["Full Color"],
    sizes: ["Large"]
  },
  {
    id: "13",
    imageUrl: "https://images.unsplash.com/photo-1715711201365-eecc5c7f8310?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    title: "Koi Fish",
    style: "Neo Traditional",
    price: 250,
    description: "Traditional koi fish sleeve with detailed scales and flowing water elements. In Japanese culture, the koi represents perseverance and good fortune.",
    keywords: ["Neo Traditional"],
    labels: [],
    colors: ["Full Color"],
    sizes: ["Large"]
  },
  {
    id: "14",
    imageUrl: "https://images.unsplash.com/photo-1772036667987-bbdf64a405b8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    title: "Butterfly",
    style: "Fine Line",
    price: 140,
    description: "Elegant fine-line butterfly with delicate wing detail. A timeless symbol of transformation and beauty, perfect for wrist or collarbone placement.",
    keywords: ["Fine Line"],
    labels: [],
    colors: ["Black & Grey"],
    sizes: ["Medium"]
  },
  {
    id: "15",
    imageUrl: "https://images.unsplash.com/photo-1635424239739-f269ff7c2fac?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    title: "Samurai",
    style: "Japanese Traditional",
    price: 300,
    description: "Warrior samurai in full armor rendered in traditional Japanese irezumi style. Represents honor, discipline, and the Bushido code.",
    keywords: ["Japanese Traditional"],
    labels: [],
    colors: ["Full Color"],
    sizes: ["Large"]
  },
  {
    id: "16",
    imageUrl: "https://images.unsplash.com/photo-1625588322602-9bdc3a0bc41e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    title: "Wings",
    style: "Neo Traditional",
    price: 260,
    description: "Spread angel wings with detailed primary and secondary feathers. A classic back or chest piece design symbolizing freedom and spiritual protection.",
    keywords: ["Neo Traditional"],
    labels: [],
    colors: ["Black & Grey"],
    sizes: ["Large"]
  },
  {
    id: "17",
    imageUrl: "https://images.unsplash.com/photo-1717362077739-ca9fde40ced9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    title: "Anchor",
    style: "American Traditional",
    price: 120,
    description: "Nautical anchor in bold traditional style. A classic sailor tattoo representing stability, home, and safe harbor after long voyages at sea.",
    keywords: ["American Traditional"],
    labels: ["Anchor"],
    colors: ["Color"],
    sizes: ["Small"]
  },
  {
    id: "18",
    imageUrl: "https://images.unsplash.com/photo-1539308973628-e08d53864d9a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    title: "Floral Sleeve",
    style: "Neo Traditional",
    price: 350,
    description: "Full floral sleeve tattoo featuring roses, peonies, and botanical elements in vibrant color. A cohesive, garden-inspired sleeve design.",
    keywords: ["Neo Traditional"],
    labels: [],
    colors: ["Full Color"],
    sizes: ["Large"]
  },
  {
    id: "19",
    imageUrl: "https://images.unsplash.com/photo-1757529151032-45880811f78d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    title: "Serpent",
    style: "Neo Traditional",
    price: 180,
    description: "Coiled serpent with detailed scale patterns. A symbol of transformation, wisdom, and duality — one of the oldest tattoo motifs in human history.",
    keywords: ["Neo Traditional"],
    labels: ["Snake"],
    colors: ["Color"],
    sizes: ["Medium"]
  },
  {
    id: "20",
    imageUrl: "https://images.unsplash.com/photo-1612526445755-02f96c307543?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=800",
    title: "Heart",
    style: "American Traditional",
    price: 140,
    description: "Classic American Traditional heart with bold red coloring and strong outlines. The quintessential sailor tattoo — timeless, bold, and full of love.",
    keywords: ["American Traditional"],
    labels: ["Heart"],
    colors: ["Full Color"],
    sizes: ["Small"]
  },
];
